### PR TITLE
Fix errors and missing functions in the ChangeLog

### PR DESCRIPTION
**Pull request by traversaro**
The wbm_getStates/wbm_getState mix was particularly nasty, because I searched for all the occurrences of `wbm_getState` to change the signature. 

@gabrielenava @Ganimed please check if I got something wrong.

### CODE REVIEW

**Comment by Ganimed** [comment]
This was an _typing error_ with copy & paste. The correct name of the function is "**wbm_getState**". I did not renamed the name of the wrapper-function. The function has still the old name.

**Comment by Ganimed** [comment]
There is still one overseen copy & paste error in the last line of the change log:
    _"wbm_initialise --> wbm_initialise"_

it should be: wbm_modelInitialise --> wbm_modelInitialize

**Comment by Ganimed** [comment]
Fixed. The second release has the version number 0.1.1. But there is still mentioned version 0.2. Should I change it to 0.1.1?

**Comment by traversaro** [comment]
No. 0.1.1 is the tag of the commit before the merge, https://github.com/robotology/mex-wholebodymodel/blob/master/CHANGELOG.md#011 . We should tag the 0.2 release as one of recent commits in master.

**Comment by Ganimed** [comment]
Now I understand. The version numbers confused me a bit. But I did not changed them. I fixed only the copy & paste error.

Furthermore, last week I made some further optimizations in the C++ code.
@gabrielenava: You can merge again my branch into your branch. If everything works fine, you can merge it again into the master.

P.S. These were more or less the last optimizations/changes in the subroutine. Now I cannot find anything more to optimize. But if someone finds a bug or has problems under _MS-Windows_ or _MacOS_. Then please let me know.

**Pull request merged**
