### PR TITLE
Fix memory deallocation and kinematic energy conservation test

### PR DESCRIPTION
**Pull request by traversaro**
This was meant to be a branch for fixing the kinetic energy conservation test, but I still failed to to this. UPDATE: Kinematic Energy test finally fixed! 

However, working toward this goal I solved several bugs (namely https://github.com/robotology/mex-wholebodymodel/issues/47 and https://github.com/robotology/mex-wholebodymodel/issues/46) that drastically improve the stability of the `mex-wholebodymodel`.

In the process of fixing this bugs I also fixed all the `-Wall` warnings, at least in GCC. 

As always, to get the diff without the whitespace changes (sorry for the trouble, but the repo was full of trailing whitespace) you can check https://github.com/robotology/mex-wholebodymodel/pull/49/files?w= . 

The diff is quite huge, so perhaps to get an understanding on what happened in the code it is easier to inspect the individual commits.

### CODE REVIEW

**Comment by traversaro** [comment]
@naveenoid do you have any plan to have a look at this in the next 24 hours? If you don't have time I will merge, so we can continue to work on the other issues of the repo.

**Comment by naveenoid** [comment]
Looking at it now.

On Fri, Oct 23, 2015 at 4:43 PM, Silvio Traversaro <notifications@github.com

**Comment by naveenoid** [comment]
Im good to merge except for weird empty function body will take a look on that today again

**Comment by traversaro** [comment]
Ok, let me know when we can merge.

**Comment by traversaro** [comment]
@gabrielenava can you check if everything still works for you?

**Comment by gabrielenava** [comment]
ok ! I'll do update all and than test the code before noon

**Comment by DanielePucci** [comment]
Corrected version: "ok ! I'll update the software and perform the tests on the code before noon"

**Comment by gabrielenava** [comment]
I did the tests on balancing code and seems everything is working well

**Comment by naveenoid** [comment]
good job. I checked too and seems fine.

**Pull request merged**
